### ISSUE TITLE
404 when exporting a file

### ISSUE THREAD

**Issue by matthewhegarty** [saritasa-nest/django-import-export-extensions#67]
I set up my first project and it looks really promising.

My first export of 96k rows ran successfully, and I can see that the file has been created on the container. My `MEDIA_ROOT` is at:

```
MEDIA_ROOT = "/home/app/media"
```

And the file has been created in the correct place on the container:

```
/home/app/media/import_export_extensions/export/5e5e6122-2323-40f8-bbf7-7a2acf6306d5/books-2024-11-20.csv
```

However, when I click the download link, I get a 404:

(link: http://localhost:8000/import_export_extensions/export/5e5e6122-2323-40f8-bbf7-7a2acf6306d5/books-2024-11-20.csv)

Is it that the link is not referring to [`MEDIA_ROOT`](https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-MEDIA_ROOT) ?

**Comment by Eg0ra** [comment]
Hi @matthewhegarty,

I guess you should try to include `MEDIA_URL` to the **project's** `urlpatterns`, for example:

```python
# urls.py
if settings.DEBUG:
	urlpatterns += static(
		settings.MEDIA_URL,
		document_root=settings.MEDIA_ROOT,
	)
```

https://docs.djangoproject.com/en/dev/howto/static-files/#serving-files-uploaded-by-a-user-during-development

**Comment by matthewhegarty** [comment]
Yes, that was the solution, thank you.
