### ISSUE TITLE
UI hangs on import

### ISSUE THREAD

**Issue by matthewhegarty** [saritasa-nest/django-import-export-extensions#68]
I have a simple application deployed with Celery.  This may be expected behaviour but it seemed a bit confusing.

I import a large file (20k rows), the UI displays:

![image](https://github.com/user-attachments/assets/0e9b948d-b1bd-4761-aff6-506f41339aed)

- The `parse_data_task` is called in the celery worker.  
- The import row appears in the db with a status of 'PARSING'.
- After 2 mins the db state changes to 'PARSED'
- The Web UI doesn't change, but if I click browser refresh I see

![image](https://github.com/user-attachments/assets/7526b780-754b-4cd7-a3d4-95a5f496be00)

I would expect to see a preview of the data here but the rows are empty.

If I click confirm, I see (DB status changes to 'IMPORTING')

![image](https://github.com/user-attachments/assets/c9d8bc0b-4760-4417-bc4c-812c6acfad4f)

After around 2 mins the DB status changes to 'IMPORTED' (the UI doesn't refresh).  If I click back to the main home page, I can see the book entries, although it appears that there is one less.  DB count is 19,999, file count is 20,000 (excluding header).

**Comment by matthewhegarty** [comment]
> looks like js code from static didn't work in your app

Yes, this is the issue.  Affects Google Chrome - it works fine in Safari.

There's no errors in the console.  What's happening is that [this line](https://github.com/saritasa-nest/django-import-export-extensions/blob/4c69948c4872b941d4443ac17c26a74b9f5896e4/import_export_extensions/static/import_export_extensions/js/widgets/progress_bar.js#L59) is not being called by default.  However, if I refresh the page immediately after submitting the file for import, then the line is hit and the progress bar is displayed correctly.  The same happens for the 'confirm' step.

So something is stopping the progress bar logic from being initiated on Chrome.

![image](https://github.com/user-attachments/assets/88f35456-c597-40b0-aa8b-69270784466a)

This is Chrome 130.0.6723.92 on Mac OS

**Comment by matthewhegarty** [comment]
btw - it works fine for exports

**Comment by matthewhegarty** [comment]
I wonder if it's a timing issue? 

I notice [here](https://github.com/saritasa-nest/django-import-export-extensions/blob/4c69948c4872b941d4443ac17c26a74b9f5896e4/import_export_extensions/templates/admin/import_export_extensions/celery_import_status.html#L41) that the progress bar is only displayed if the job status is in progress_statuses.  Perhaps the page is rendering before the task changes the state to 'in progress'.

I set the debugger and notice that [url is null](https://github.com/saritasa-nest/django-import-export-extensions/blob/4c69948c4872b941d4443ac17c26a74b9f5896e4/import_export_extensions/static/import_export_extensions/js/widgets/progress_bar.js#L38).

**Comment by Eg0ra** [comment]
> I wonder if it's a timing issue?

Yes, during my investigation, I found that the task doesn't have time to change status, thanks for help
I am preparing a correction in #71. Could you check if it will work for you?

> I can see the book entries, although it appears that there is one less. DB count is 19,999, file count is 20,000

What about the missing object after import, did you find it?)

**Comment by matthewhegarty** [comment]
Yes, that has fixed it, thanks.

btw the empty data on preview issue was because I had `skip_html_diff` enabled in my Resource class.

> What about the missing object after import, did you find it?)

No 😞  - still one short - I'll raise a separate issue.
