### ISSUE TITLE
import process crashes with invalid file (no errors reported)

### ISSUE THREAD

**Issue by matthewhegarty** [saritasa-nest/django-import-export-extensions#74]
I am running the example application on Docker.  I find that the process crashes when using an incomplete 'artists' file.  I don't see any error message or warnings, the celery container eventually crashes with 'out of memory' error.

To reproduce (I have a branch [here](https://github.com/matthewhegarty/django-import-export-extensions/tree/mrh-additions) which runs the application in Docker - `docker compose up --build`):

1. Go to Artist import
2. Leave Resource on default of 'ArtistResourceWithM2M'
3. Choose the attached file (change name to 'artists.csv')
4. Click import

You will see the following requests:

![image](https://github.com/user-attachments/assets/6da98f56-4087-4b16-a035-d6fb87a76289)

In my Docker instance (running on MacOS) I see this error after about 5 mins:

```
[ERROR] Worker (pid:19) was sent SIGKILL! Perhaps out of memory?
```

No other errors are reported.

If you import the file 'artists-sm.csv' it runs fine (ensure an 'Instrument' FK exists with id=1).

[artists.csv.txt](https://github.com/user-attachments/files/17923869/artists.csv.txt)
[artists-sm.csv.txt](https://github.com/user-attachments/files/17923868/artists-sm.csv.txt)

**Comment by matthewhegarty** [comment]
btw - it's taken me a little while to get the test_project up and running - I'm happy to add this to the documentation if that's of interest?

**Comment by Eg0ra** [comment]
Hi @matthewhegarty ,

I found out the reason for out of memory, it happens when trying to render template. I [removed extra loop](https://github.com/saritasa-nest/django-import-export-extensions/pull/71/files#diff-88c66d60a26c73187999400ce10d5b8332baa657253ef20368e28498c1f4a25eL102-R110), please try, will this fix your error?

**Comment by matthewhegarty** [comment]
Thanks - AFAICT it has the same issue.  I merged your branch and pushed [here](https://github.com/matthewhegarty/django-import-export-extensions/tree/mrh-additions).

btw - am in the [django-import-export discord](https://discord.com/channels/1240294048653119508/1240294049122877543) if it helps.

**Comment by matthewhegarty** [comment]
I still get the same issue when using containers (it's the server container which crashes due to memory issues).

The process works fine when I run celery and server in my IDE (PyCharm), though it takes ~45 seconds to prepare the preview for importing 2k files (see artists.csv in thread above).  It would be ideal if the UI indicated that parsing has started - at the moment there is no feedback to the user.

**Comment by Eg0ra** [comment]
@matthewhegarty So, i think problem inside your [Dockerfile](https://github.com/matthewhegarty/django-import-export-extensions/blob/mrh-additions/docker/server/Dockerfile#L24)

>RUN pip install poetry django-import-export-extensions

This command will install latest released version from pypi, which still has the issue.
