### ISSUE TITLE
Auto select file format according to file suffix

### ISSUE THREAD

**Issue by matthewhegarty** [saritasa-nest/django-import-export-extensions#75]
django-import-export has js logic to autofill the 'format' field based on the file suffix.  Source is [here](https://github.com/django-import-export/django-import-export/blob/main/import_export/static/import_export/guess_format.js).
It would be a nice addition to have this in the UI.

![upload1](https://github.com/user-attachments/assets/be8d6ea0-499d-46e6-acdb-d5f568cca482)

**Comment by Eg0ra** [comment]
This has already been fixed in #71 )
