### ISSUE TITLE
can export filefield?

### ISSUE THREAD

**Issue by H0nGzA1** [saritasa-nest/django-import-export-extensions#9]
now i have a requirement, need export excel

<img width="1777" alt="image" src="https://github.com/saritasa-nest/django-import-export-extensions/assets/21973212/d274bdc0-9a4a-4ee5-a1e9-423dbdccc08f">
 like this

**Comment by NikAzanov** [comment]
As far as I understand, you want to insert images into excel instead of links. But this package just works with tablib, which does not support this functionality.

You can try to define your own custom widget for export to achieve your goal.
